"""Chnage recipe_image_url data type

Revision ID: d09684051709
Revises: 2226d5b6c942
Create Date: 2023-12-15 21:18:40.811927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09684051709'
down_revision = '2226d5b6c942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'recipe_image_url', new_column_name='recipe_image_url', type_=sa.String(length=255))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('recipe', 'recipe_image_url', new_column_name='recipe_image_url', type_=sa.LargeBinary())
    op.execute('PRAGMA foreign_keys=off;')
    op.execute('BEGIN TRANSACTION;')
    op.execute('CREATE TEMPORARY TABLE recipe_backup AS SELECT * FROM recipe;')
    op.execute('DROP TABLE recipe;')
    op.execute('CREATE TABLE recipe (id INTEGER NOT NULL, user_id INTEGER NOT NULL, recipe_name VARCHAR(255) NOT NULL, recipe_description TEXT NOT NULL, ingredients TEXT NOT NULL, recipe_image_url VARCHAR(255) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES user (id));')
    op.execute('INSERT INTO recipe SELECT * FROM recipe_backup;')
    op.execute('DROP TABLE recipe_backup;')
    op.execute('COMMIT;')
    op.execute('PRAGMA foreign_keys=on;')

    # ### end Alembic commands ###
